version: "3"
services:
  auctioner:
    image: auctioner:latest
    env_file:
     - ./.env 
    restart: always
    ports: 
      - "8080:80"
  bidder1:
    image: bidder:latest
    restart: always
    ports: 
      - "8081:80"
  bidder2:
    image: bidder:latest
    restart: always
    ports: 
      - "8082:80"
  bidder3:
    image: bidder:latest
    restart: always
    ports: 
      - "8083:80"
  bidder4:
    image: bidder:latest
    restart: always
    ports: 
      - "8084:80"                