version: "3"
services:
  bidder:
    build: 
      context: ./Bidder
      dockerfile: Dockerfile
    image: bidder
  auctioner:
    build:
      context: ./Auctioner
      dockerfile: Dockerfile
    image: auctioner      
